# Site settings
title: Realtime Visual JS
email: thomas.hofmann2003@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Realtime plotting and configuration PWA.
baseurl: "/realtimeVisualJS" # the subpath of your site, e.g. /blog
url: "https://thomint.github.io" # the base hostname & protocol for your site

# Build settings
markdown: none
theme: minima

# Directory settings
include:
  - _pages
  - _posts
  - _data
  - node_modules

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - "*.markdown"
  - "*.md"
  - "*.mkd"
  - "*.mkdn"
  - "*.mdwn"
  - "*.mdown"
  - "*.mdtxt"
  - "*.mdtext"

# Enable GitHub Pages
github:
  is_project_page: false

# Other settings (customize as needed)
# Add any additional plugins or configurations here

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
